# Generated by Django 4.0.4 on 2022-06-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puppies', to='main_app.dog')),
            ],
        ),
    ]
