# Generated by Django 4.0.4 on 2022-06-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_puppy'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppy',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
